### PR TITLE
fix: preserve original callNode in localizeCompiler

### PR DESCRIPTION
**Pull request by benjamin-hodgson**
I noticed this bug while trying to merge `develop` into #24.

The `localizeCompiler` was behaving differently in single-locale and multi-locale mode. In single locale mode its `callNode` was the original call to `__`, whereas in multi-locale mode it was the placeholder function. We don't want to leak the placeholder function through the API (since it's an implementation detail), plus `localizeCompiler` writers will typically want access to the original function I think (especially after #24 is merged).

I fixed it by changing the placeholder's argument to be the original `__` call, rather than `__`'s arguments.

### CODE REVIEW

**Comment by privatenumber** [comment]
If the only difference is the function name, we can just rewrite the `name` property back for the `localizeCompiler` function because that's how it's converted to a placeholder in the first place:
https://github.com/privatenumber/webpack-localize-assets-plugin/blob/7c065eba7cc1f47d2cd1455c9a017aee9c50aa1b/src/multi-locale.ts#L86

**Comment by benjamin-hodgson** [comment]
With #24, you won't know what that name was

**Comment by privatenumber** [comment]
Thanks!

**Pull request merged**
